apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense-service
          image: expense-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
