apiVersion: v1
kind: Service
metadata:
  name: expense-service
spec:
  selector:
    app: expense-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: summary-service
spec:
  selector:
    app: summary-service
  ports:
    - port: 8001
      targetPort: 8001
